
CREATE EXTERNAL TABLE IF NOT EXISTS ${DATABASE}.${TABLE_NAME} (
${COLUMNS}
)
PARTITIONED BY (${PARTITION_COLUMN} DATE)
STORED AS PARQUET
LOCATION 's3://${S3_BUCKET}/prymal_agent/${TABLE_NAME}/'
TBLPROPERTIES (
    'comment'='${TABLE_DESCRIPTION}'
);
