CREATE EXTERNAL TABLE IF NOT EXISTS ${DATABASE}.${TABLE_NAME} (
${COLUMNS}
)
${PARTITION_CLAUSE}
STORED AS PARQUET
LOCATION 's3://${S3_BUCKET}/${S3_LOCATION}'
TBLPROPERTIES (
    'comment'='${TABLE_COMMENT}'
);
