
table:
  name: "shipbob_current_inventory"
  description: "One record per inventory item in ShipBob. ShipBob is where product inventory is maintained, and shows the inventory level of products that are sold across multiple sales channel. The 'id' column is the distinct identifier for a product and maps to the inventory_id in ShipBob order data. The latest snapshot date contains the current inventory levels as of the partition_date column"
  partition_column: "partition_date"
columns:
  - name: "id"
    type: "bigint"
    comment: "shipbob inventory ID (unique identifier for a physical product across all sales channels. Use this to map store listings to inventory items)"
  - name: "name"
    type: "string"
    comment: "name of the product"
  - name: "is_digital"
    type: "boolean"
    comment: "whether the product is a digital item"
  - name: "is_case_pick"
    type: "boolean"
    comment: "whether the product is case picked"
  - name: "is_lot"
    type: "boolean"
    comment: "whether the product is part of a lot"
  - name: "total_fulfillable_quantity"
    type: "bigint"
    comment: "total inventory qty available to be fulfilled (after accounting for existing unfilled orders)"
  - name: "total_onhand_quantity"
    type: "bigint"
    comment: "total inventory qty available (not accounting for unfilled orders)"
  - name: "total_committed_quantity"
    type: "bigint"
    comment: "total inventory qty commited to orders to be fulfilled"
  - name: "total_sellable_quantity"
    type: "bigint"
    comment: "total inventory qty available to be sold"
  - name: "total_awaiting_quantity"
    type: "bigint"
    comment: "total inventory awaiting (in route to fulfilment center)"
  - name: "total_exception_quantity"
    type: "bigint"
    comment: "total inventory qty commited to orders above and beyond available inventory"
  - name: "total_internal_transfer_quantity"
    type: "bigint"
    comment: "total inventory qty being transferred to/from other fultillment center locations"
  - name: "total_backordered_quantity"
    type: "bigint"
    comment: "total units on back order"
  - name: "is_active"
    type: "boolean"
    comment: "whether or not the product is active"
