name: Prymal Agent Report Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs at AM every day


jobs:
  prymal_agent_reports:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Print wd
        run: |
          pwd
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run job
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GLUE_DATABASE_NAME: ${{ secrets.GLUE_DATABASE_NAME }}
        working-directory: src/prymal_agent/shipbob_retention_by_cohort_month
        run: python main.py

  
      - run: echo "Job status - ${{ job.status }}."
  